{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: "eirini"
  template:
    metadata:
      labels:
        name: "eirini"
      annotations:
        quarks.cloudfoundry.org/restart-on-update: "true"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "opi"
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: opi.yml
              path: opi.yml
        - name: cc-certs
          projected:
              sources:
              - secret:
                  name: "{{ .Values.eirini.opi.tls.opiCapiClient.secretName }}"
                  items:
                  - key: "{{ .Values.eirini.opi.tls.opiCapiClient.certPath }}"
                    path: tls.crt
                  - key: "{{ .Values.eirini.opi.tls.opiCapiClient.keyPath }}"
                    path: tls.key
              - secret:
                  name: "{{ .Values.eirini.opi.tls.capi.secretName }}"
                  items:
                  - key: "{{ .Values.eirini.opi.tls.capi.caPath }}"
                    path: ca.crt
        - name: eirini-certs
          projected:
              sources:
              - secret:
                  name: "{{ .Values.eirini.opi.tls.opiServer.secretName }}"
                  items:
                  - key: "{{ .Values.eirini.opi.tls.opiServer.certPath }}"
                    path: tls.crt
                  - key: "{{ .Values.eirini.opi.tls.opiServer.keyPath }}"
                    path: tls.key
              - secret:
                  name: "{{ .Values.eirini.opi.tls.eirini.secretName }}"
                  items:
                  - key: "{{ .Values.eirini.opi.tls.eirini.caPath }}"
                    path: ca.crt
      securityContext:
        runAsNonRoot: true
      containers:
      - name: opi
        image: eirini/opi@{{ .Files.Get "assets/versions/opi" }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
        - name: cc-certs
          mountPath: /etc/cf-api/certs
        - name: eirini-certs
          mountPath: /etc/eirini/certs
        ports:
        - containerPort: 8085
          name: https
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
{{- end }}
