{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
{{- if .Values.eirini.opi.metrics.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini-metrics"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: "eirini-metrics"
  template:
    metadata:
      labels:
        name: "eirini-metrics"
      annotations:
        quarks.cloudfoundry.org/restart-on-update: "true"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "eirini-metrics"
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: metrics.yml
              path: metrics.yml
        - name: cf-secrets
          projected:
            sources:
            - secret:
                name: "{{ .Values.eirini.opi.metrics.tls.client.secretName }}"
                items:
                - key: "{{ .Values.eirini.opi.metrics.tls.client.certPath }}"
                  path: tls.crt
                - key: "{{ .Values.eirini.opi.metrics.tls.client.keyPath }}"
                  path: tls.key
            - secret:
                name: "{{ .Values.eirini.opi.metrics.tls.server.secretName }}"
                items:
                - key: "{{ .Values.eirini.opi.metrics.tls.server.caPath }}"
                  path: ca.crt
      securityContext:
        runAsNonRoot: true
      containers:
      - name: metrics-collector
        image: eirini/metrics-collector@{{ .Files.Get "assets/versions/metrics-collector" }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini-metrics/config
        - name: cf-secrets
          mountPath: /etc/loggregator/certs
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
{{- end }}
{{- end }}
